spring.application.name=book-management-service

# ===================
# DATABASE CONFIG
# ===================

spring.datasource.url=jdbc:postgresql://localhost:5432/book_management
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.drive-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#port
server.port=8080